line-length = 200
target-version = "py311"

[lint]
select = ["E", "F", "E722", "B006"]
ignore = []

[lint.per-file-ignores]
"Display/BallisticThreader.py" = ["E501"]
"Display/disptest*.py" = ["E402", "F403", "F405"]
"Display/disp2test*.py" = ["E402", "F403", "F405"]
